export const GET_AGENDA_LESSONS_REQUEST = 'GET_AGENDA_LESSONS_REQUEST';
export const GET_AGENDA_LESSONS_SUCCESS = 'GET_AGENDA_LESSONS_SUCCESS';
export const GET_AGENDA_LESSONS_FAIL = 'GET_AGENDA_LESSONS_FAIL';
