export const GET_AGENDA_LESSONS_REQUEST = 'GET_AGENDA_LESSONS_REQUEST';
export const GET_AGENDA_LESSONS_SUCCESS = 'GET_AGENDA_LESSONS_SUCCESS';
export const GET_AGENDA_LESSONS_FAIL = 'GET_AGENDA_LESSONS_FAIL';

export const ATTEND_AGENDA_LESSONS_REQUEST = 'ATTEND_AGENDA_LESSONS_REQUEST';
export const ATTEND_AGENDA_LESSONS_SUCCESS = 'ATTEND_AGENDA_LESSONS_SUCCESS';
export const ATTEND_AGENDA_LESSONS_FAIL = 'ATTEND_AGENDA_LESSONS_FAIL';

export const UNATTEND_AGENDA_LESSONS_REQUEST =
  'UNATTEND_AGENDA_LESSONS_REQUEST';
export const UNATTEND_AGENDA_LESSONS_SUCCESS =
  'UNATTEND_AGENDA_LESSONS_SUCCESS';
export const UNATTEND_AGENDA_LESSONS_FAIL = 'UNATTEND_AGENDA_LESSONS_FAIL';

export const TOCREDIT_AGENDA_LESSONS_REQUEST =
  'TOCREDIT_AGENDA_LESSONS_REQUEST';
export const TOCREDIT_AGENDA_LESSONS_SUCCESS =
  'TOCREDIT_AGENDA_LESSONS_SUCCESS';
export const TOCREDIT_AGENDA_LESSONS_FAIL = 'TOCREDIT_AGENDA_LESSONS_FAIL';
