export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAIL = 'GET_USER_INFO_FAIL';

export const ADD_USER_LESSON_REQUEST = 'ADD_USER_LESSON_REQUEST';
export const ADD_USER_LESSON_SUCCESS = 'ADD_USER_LESSON_SUCCESS';
export const ADD_USER_LESSON_FAIL = 'ADD_USER_LESSON_FAIL';

export const UPDATE_USER_LESSON_REQUEST = 'UPDATE_USER_LESSON_REQUEST';
export const UPDATE_USER_LESSON_SUCCESS = 'UPDATE_USER_LESSON_SUCCESS';
export const UPDATE_USER_LESSON_FAIL = 'UPDATE_USER_LESSON_FAIL';
