export const GET_PAYTRACKER_REQUEST = 'GET_PAYTRACKER_REQUEST';
export const GET_PAYTRACKER_SUCCESS = 'GET_PAYTRACKER_SUCCESS';
export const GET_PAYTRACKER_FAIL = 'GET_PAYTRACKER_FAIL';

export const UPDATE_PAYTRACKER_CONTACTED_REQUEST =
  'UPDATE_PAYTRACKER_CONTACTED_REQUEST';
export const UPDATE_PAYTRACKER_CONTACTED_SUCCESS =
  'UPDATE_PAYTRACKER_CONTACTED_SUCCESS';
export const UPDATE_PAYTRACKER_CONTACTED_FAIL =
  'UPDATE_PAYTRACKER_CONTACTED_FAIL';

export const PAYLESSONS_PAYTRACKER_REQUEST = 'PAYLESSONS_PAYTRACKER_REQUEST';
export const PAYLESSONS_PAYTRACKER_SUCCESS = 'PAYLESSONS_PAYTRACKER_SUCCESS';
export const PAYLESSONS_PAYTRACKER_FAIL = 'PAYLESSONS_PAYTRACKER_FAIL';
