export const GET_STUDENTS_REQUEST = 'GET_STUDENT_REQUEST';
export const GET_STUDENTS_SUCCESS = 'GET_STUDENT_SUCCESS';
export const GET_STUDENTS_FAIL = 'GET_STUDENT_FAIL';

export const ADD_STUDENTS_REQUEST = 'ADD_STUDENT_REQUEST';
export const ADD_STUDENTS_SUCCESS = 'ADD_STUDENT_SUCCESS';
export const ADD_STUDENTS_FAIL = 'ADD_STUDENT_FAIL';
