export const GET_STUDENTS_REQUEST = 'GET_STUDENT_REQUEST';
export const GET_STUDENTS_SUCCESS = 'GET_STUDENT_SUCCESS';
export const GET_STUDENTS_FAIL = 'GET_STUDENT_FAIL';

export const ADD_STUDENTS_REQUEST = 'ADD_STUDENT_REQUEST';
export const ADD_STUDENTS_SUCCESS = 'ADD_STUDENT_SUCCESS';
export const ADD_STUDENTS_FAIL = 'ADD_STUDENT_FAIL';

export const GET_STUDENT_INFO_REQUEST = 'GET_STUDENT_INFO_REQUEST';
export const GET_STUDENT_INFO_SUCCESS = 'GET_STUDENT_INFO_SUCCESS';
export const GET_STUDENT_INFO_FAIL = 'GET_STUDENT_INFO_FAIL';

export const UPDATE_STUDENT_INFO_REQUEST = 'UPDATE_STUDENT_INFO_REQUEST';
export const UPDATE_STUDENT_INFO_SUCCESS = 'UPDATE_STUDENT_INFO_SUCCESS';
export const UPDATE_STUDENT_INFO_FAIL = 'UPDATE_STUDENT_INFO_FAIL';

export const SAVE_PURCHASE_STUDENT_REQUEST = 'SAVE_PURCHASE_STUDENT_REQUEST';
export const SAVE_PURCHASE_STUDENT_SUCCESS = 'SAVE_PURCHASE_STUDENT_SUCCESS';
export const SAVE_PURCHASE_STUDENT_FAIL = 'SAVE_PURCHASE_STUDENT_FAIL';

export const PURCHASE_STUDENT_LESSON_REQUEST =
  'PURCHASE_STUDENT_LESSON_REQUEST';
export const PURCHASE_STUDENT_LESSON_SUCCESS =
  'PURCHASE_STUDENT_LESSON_SUCCESS';
export const PURCHASE_STUDENT_LESSON_FAIL = 'PURCHASE_STUDENT_LESSON_FAIL';
