import Private from './Private';

export const data = [
  {
    typeName: 'ISC',
    date: '2022-5-4',
    type: 'group',
    time: '13:00-14:00',
    students: [
      { name: 'richard', attendance: true },
      { name: 'Samuel', attendance: false },
      { name: 'Dwaggie', attendance: true },
      { name: 'Michael', attendance: false },
      { name: 'Luke', attendance: true },
    ],
  },
  {
    typeName: 'JuniorPrivate',
    date: '2022-5-3',
    type: 'group',
    students: [
      { name: 'richard' },
      { name: 'Samuel' },
      { name: 'Dwaggie' },
      { name: 'Michael' },
      { name: 'Luke' },
    ],
  },
  {
    typeName: 'jay',
    date: '2022-5-3',
    type: 'group',
    students: [
      { name: 'richard' },
      { name: 'Samuel' },
      { name: 'Dwaggie' },
      { name: 'Michael' },
      { name: 'Luke' },
    ],
  },
  {
    typeName: 'super',
    date: '2022-5-3',
    type: 'group',
    students: [
      { name: 'richard' },
      { name: 'Samuel' },
      { name: 'Dwaggie' },
      { name: 'Michael' },
      { name: 'Luke' },
    ],
  },
  {
    typeName: 'batman',
    date: '2022-5-3',
    type: 'group',
    students: [
      { name: 'richard' },
      { name: 'Samuel' },
      { name: 'Dwaggie' },
      { name: 'Michael' },
      { name: 'Luke' },
    ],
  },
  {
    typeName: 'megaman',
    date: '2022-5-3',
    type: 'group',
    students: [
      { name: 'richard' },
      { name: 'Samuel' },
      { name: 'Dwaggie' },
      { name: 'Michael' },
      { name: 'Luke' },
    ],
  },
  {
    typeName: 'JuniorPrivate',
    date: '2022-5-3',
    type: 'group',
    students: [
      { name: 'richard' },
      { name: 'Samuel' },
      { name: 'Dwaggie' },
      { name: 'Michael' },
      { name: 'Luke' },
    ],
  },
  {
    typeName: 'daniel',
    date: '2022-5-3',
    type: 'group',
    students: [
      { name: 'richard' },
      { name: 'Samuel' },
      { name: 'Dwaggie' },
      { name: 'Michael' },
      { name: 'Luke' },
    ],
  },
  {
    typeName: 'manny',
    date: '2022-5-3',
    type: 'group',
    students: [
      { name: 'richard' },
      { name: 'Samuel' },
      { name: 'Dwaggie' },
      { name: 'Michael' },
      { name: 'Luke' },
    ],
  },
  {
    typeName: 'liger',
    date: '2022-5-3',
    type: 'group',
    students: [
      { name: 'richard' },
      { name: 'Samuel' },
      { name: 'Dwaggie' },
      { name: 'Michael' },
      { name: 'Luke' },
    ],
  },
  {
    typeName: 'cringer',
    date: '2022-5-3',
    type: 'group',
    students: [
      { name: 'richard' },
      { name: 'Samuel' },
      { name: 'Dwaggie' },
      { name: 'Michael' },
      { name: 'Luke' },
    ],
  },
  {
    typeName: 'handsome league',
    date: '2022-5-3',
    type: 'group',
    students: [
      { name: 'richard' },
      { name: 'Samuel' },
      { name: 'Dwaggie' },
      { name: 'Michael' },
      { name: 'Luke' },
    ],
  },
  {
    typeName: 'JuniorPrivate',
    date: '2022-5-3',
    type: 'group',
    students: [
      { name: 'richard' },
      { name: 'Samuel' },
      { name: 'Dwaggie' },
      { name: 'Michael' },
      { name: 'Luke' },
    ],
  },
  {
    typeName: 'Team 1',
    date: '2022-5-2',
    type: 'group',
    students: [
      { name: 'richard' },
      { name: 'Samuel' },
      { name: 'Dwaggie' },
      { name: 'Michael' },
      { name: 'Luke' },
    ],
  },
  { typeName: 'T2', date: '2022-5-3', type: 'group' },
  {
    typeName: 'Richard',
    date: '2022-5-2',
    time: '13:00-14:00',
    type: 'junior private',
  },
  {
    typeName: 'Samuel',
    date: '2022-5-3',
    time: '13:00-14:00',
    type: 'senior private',
    lessons: { juniorPrivate: 1, seniorPrivate: 2, ISC: 3 },
  },
  {
    typeName: 'Ryley',
    date: '2022-5-3',
    time: '13:00-14:00',
    type: 'headcoach private',
  },
  {
    typeName: 'Luke',
    date: '2022-5-3',
    time: '13:00-14:00',
    type: 'junior private',
  },
  {
    typeName: 'Branddon',
    date: '2022-5-3',
    time: '13:00-14:00',
    type: 'junior private',
  },
  {
    typeName: 'Shaina Anne',
    date: '2022-5-3',
    time: '13:00-14:00',
    type: 'junior private',
  },
];
